### ISSUE TITLE
Separating tips into Python programs.

### ISSUE THREAD

**Issue by yawboakye** [sahands/python-by-example#3]
I want to work on separating the tips into Python programs with a little bit more explanations. Is that a good idea?

**Comment by sahands** [comment]
Sure. That would make it into a new article, which you are welcome to own and host as long as you give credit to the original article as the initial source.

**Comment by yawboakye** [comment]
I'd push it back here, and you can just update the original article with the new changes. I'm not interested in directing anyone away from this repo or the original article.
